jobs:
  - name: supplypike-edi_stage_platform_create_secrets
    type: runSh
    steps:
      - IN: supplypike-edi_test_platform_integration_tests
      - IN: stage_platform_kube_cli_config
      - IN: platform_docker_cli_config
      - IN: supplypike-edi_stage_platform_secrets
      - IN: platform_secrets_password
      - TASK:
          name: create_secrets
          script:
            - export RABBIT_VHOST=$(docker run -e PASSWORD=$ENCRYPTION_KEY --entrypoint yarn casestack/cgen-server --silent decrypt $RABBIT_VHOST)
            - export RABBIT_LOGIN=$(docker run -e PASSWORD=$ENCRYPTION_KEY --entrypoint yarn casestack/cgen-server --silent decrypt $RABBIT_LOGIN)
            - export RABBIT_PASSWORD=$(docker run -e PASSWORD=$ENCRYPTION_KEY --entrypoint yarn casestack/cgen-server --silent decrypt $RABBIT_PASSWORD)
            - export MONGO_CREDENTIALS=$(docker run -e PASSWORD=$ENCRYPTION_KEY --entrypoint yarn casestack/cgen-server --silent decrypt $MONGO_CREDENTIALS)
            - export CONNECT_PASSWORD=$(docker run -e PASSWORD=$ENCRYPTION_KEY --entrypoint yarn casestack/cgen-server --silent decrypt $CONNECT_PASSWORD)
            - export INTERNAL_USER=$(docker run -e PASSWORD=$ENCRYPTION_KEY --entrypoint yarn casestack/cgen-server --silent decrypt $INTERNAL_USER)
            - export INTERNAL_PASSWORD=$(docker run -e PASSWORD=$ENCRYPTION_KEY --entrypoint yarn casestack/cgen-server --silent decrypt $INTERNAL_PASSWORD)
            - 'export RABBIT_VHOST=$(if [ -z $RABBIT_VHOST ]; then echo "''''"; else echo -n $RABBIT_VHOST | base64 -w 0; fi)'
            - 'export RABBIT_LOGIN=$(if [ -z $RABBIT_LOGIN ]; then echo "''''"; else echo -n $RABBIT_LOGIN | base64 -w 0; fi)'
            - 'export RABBIT_PASSWORD=$(if [ -z $RABBIT_PASSWORD ]; then echo "''''"; else echo -n $RABBIT_PASSWORD | base64 -w 0; fi)'
            - 'export MONGO_CREDENTIALS=$(if [ -z $MONGO_CREDENTIALS ]; then echo "''''"; else echo -n $MONGO_CREDENTIALS | base64 -w 0; fi)'
            - 'export CONNECT_PASSWORD=$(if [ -z $CONNECT_PASSWORD ]; then echo "''''"; else echo -n $CONNECT_PASSWORD | base64 -w 0; fi)'
            - 'export INTERNAL_USER=$(if [ -z $INTERNAL_USER ]; then echo "''''"; else echo -n $INTERNAL_USER | base64 -w 0; fi)'
            - 'export INTERNAL_PASSWORD=$(if [ -z $INTERNAL_PASSWORD ]; then echo "''''"; else echo -n $INTERNAL_PASSWORD | base64 -w 0; fi)'
            - |-
              echo "apiVersion: v1
              kind: Secret
              metadata:
                name: supplypike-edi
                namespace: platform-stage
              type: Opaque
              data:
                RABBIT_VHOST: $RABBIT_VHOST
                RABBIT_LOGIN: $RABBIT_LOGIN
                RABBIT_PASSWORD: $RABBIT_PASSWORD
                MONGO_CREDENTIALS: $MONGO_CREDENTIALS
                CONNECT_PASSWORD: $CONNECT_PASSWORD
                INTERNAL_USER: $INTERNAL_USER
                INTERNAL_PASSWORD: $INTERNAL_PASSWORD" > ./secrets.yaml
            - kubectl -n platform-stage delete secret/supplypike-edi 2>/dev/null || echo "no pre-existing secrets"
            - kubectl -n platform-stage create -f secrets.yaml
  - name: supplypike-edi_stage_platform_deploy
    type: deploy
    stabilityDuration: 120
    maxWaitTime: 300
    steps:
      - IN: supplypike-edi_stage_platform_create_secrets
      - IN: supplypike-edi_test_platform_deploy
        switch: 'off'
      - IN: stage_platform_cluster
      - IN: supplypike-edi_stage_platform_opts
        applyTo:
          - supplypike-edi_image
      - IN: supplypike-edi_stage_platform_replicas
        applyTo:
          - supplypike-edi_image
      - IN: supplypike-edi_stage_platform_params
        applyTo:
          - supplypike-edi_image
  - name: supplypike-edi_stage_platform_integration_tests
    type: runSh
    steps:
      - IN: supplypike-edi_stage_platform_deploy
      - IN: platform_docker_cli_config
      - IN: stage_platform_integration_tests_params
      - IN: stage_platform_integration_tests_secrets
      - IN: supplypike-edi_platform_integration_tests_global_state
      - TASK:
          name: integration_tests
          script:
            - export INTEGRATION_TAG=$(shipctl get_resource_version_key supplypike-edi_platform_integration_tests_global_state "INTEGRATION_TAG")
            - >-
              docker run -e BASE_URL -e RABBIT_HOST -e RABBIT_PORT -e CONNECT_USER -e RABBIT_LOGIN -e RABBIT_PASSWORD -e RABBIT_VHOST -e CONNECT_PASSWORD -e INTERNAL_USER -e INTERNAL_PASSWORD
              casestack/supplypike-edi:$INTEGRATION_TAG
    on_failure:
      - NOTIFY: platform_slack_notifications
resources:
  - name: supplypike-edi_stage_platform_secrets
    type: params
    versionTemplate:
      params:
        RABBIT_VHOST: jevkjdgd
        RABBIT_LOGIN: jevkjdgd
        RABBIT_PASSWORD: M4cP6GfKesbJ4wMgnVkvUG4bgnazKh3h
        MONGO_CREDENTIALS: 'supplypike-edi-admin:Ynk9QsekYHb1P7kNXC75EFhdv8vUmzIN'
        CONNECT_PASSWORD: password
        INTERNAL_USER: E6sKxs7DAVreMURLwlEC0ybF76SrgIZ1
        INTERNAL_PASSWORD: 8wBxdOYtCG0YlSu7W7xt6Hi5WbfaDgLw
  - name: supplypike-edi_stage_platform_opts
    type: dockerOptions
    versionTemplate:
      portMappings:
        - ':40404'
      labels:
        service: supplypike-edi
        environment: stage
        app: platform
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 300m
          memory: 300Mi
      livenessProbe:
        httpGet:
          path: /health
          port: 40404
        initialDelaySeconds: 30
        timeoutSeconds: 3
      readinessProbe:
        httpGet:
          path: /health
          port: 40404
        initialDelaySeconds: 30
        timeoutSeconds: 3
  - name: supplypike-edi_stage_platform_replicas
    type: replicas
    versionTemplate:
      count: 1
  - name: supplypike-edi_stage_platform_loadbalancer
    type: loadBalancer
    integration: staging_cluster
    versionTemplate:
      sourceName: supplypike-edi
      method: ClusterIP
      namespace: platform-stage
      ports:
        - name: port-40404
          port: 40404
          protocol: TCP
      selector:
        service: supplypike-edi
        environment: stage
        app: platform
  - name: supplypike-edi_stage_platform_params
    type: params
    versionTemplate:
      params:
        PORT: '40404'
        LOG_LEVEL: trace
        RABBIT_HOST: lion.rmq.cloudamqp.com
        RABBIT_PORT: '5672'
        MONGO_URL: 'ds037537-a0.mongolab.com:37537,ds037537-a1.mongolab.com:37537/supplypike-edi?replicaSet=rs-ds037537'
        CONNECT_USER: 5c2e1201-e62d-4b61-9bce-2fea8a4ef4c3
